-- ??? Enterprise Financial Stack: Daily Data Audit
-- Target: FIN_DB | Schema: DB2INST1 | Date: 2026-03-21

CONNECT TO FIN_DB;

-- SECTION 1: High-Level Ingest Health
SELECT TABNAME, CARD AS ROW_COUNT 
FROM SYSCAT.TABLES 
WHERE TABSCHEMA = 'DB2INST1';

-- SECTION 2: 03/21 Market Stress Watch (12 Assets)
SELECT 
    ASSET_SYMBOL, 
    CURRENT_PRICE, 
    VOLATILITY_INDEX, 
    STATUS
FROM DB2INST1.MARKET_STRESS_WATCH
ORDER BY VOLATILITY_INDEX DESC;

-- SECTION 3: Risk Inflections (Nasdaq/Big Tech)
SELECT ASSET_SYMBOL, CURRENT_PRICE 
FROM DB2INST1.MARKET_STRESS_WATCH 
WHERE ASSET_SYMBOL IN ('NQ', 'NVDA', 'MSFT', 'COMP') 
AND VOLATILITY_INDEX > 1.5;

TERMINATE;
