FROM eclipse-temurin:17-jre-focal
LABEL org.opencontainers.image.source="https://github.com/LauroBeck/docker-images"
LABEL org.opencontainers.image.description="High-performance financial system (Java 17)"
