-- Ingest Procedure for Bloomberg Surveillance Data
CREATE OR REPLACE PROCEDURE DB2INST1.SYNC_BLOOMBERG (
    IN p_nasdaq DECIMAL(10,2), 
    IN p_brent DECIMAL(10,2), 
    IN p_wti DECIMAL(10,2)
)
LANGUAGE SQL
BEGIN
    UPDATE DB2INST1.MARKET_STRESS_WATCH SET CURRENT_PRICE = p_nasdaq, STATUS = '🔴 Stress' WHERE ASSET_SYMBOL = 'COMP';
    UPDATE DB2INST1.MARKET_STRESS_WATCH SET CURRENT_PRICE = p_brent, STATUS = '🔴 CRITICAL' WHERE ASSET_SYMBOL = 'OIL';
    UPDATE DB2INST1.MARKET_STRESS_WATCH SET CURRENT_PRICE = p_wti, STATUS = '🟡 Watch' WHERE ASSET_SYMBOL = 'NY_CRUDE';
END;
