-- DB2 Schema for Maritime, Energy, and Banking Traces
CREATE TABLE DB2INST1.MARKET_STRESS_WATCH (
    ASSET_SYMBOL VARCHAR(10) PRIMARY KEY,
    CURRENT_PRICE DECIMAL(15,2),
    VOLATILITY FLOAT,
    INST_IV FLOAT,
    STATUS VARCHAR(20)
);

CREATE TABLE DB2INST1.ENERGY_EQUITIES (
    ASSET_NAME VARCHAR(30),
    TICKER VARCHAR(10),
    PRICE DECIMAL(10,2),
    STATUS VARCHAR(20),
    DAILY_VAR_PCT FLOAT
);

CREATE TABLE DB2INST1.DEFENSE_ENERGY_TRACE (
    ENTITY VARCHAR(30),
    ROLE VARCHAR(30),
    PRICE_BUDGET VARCHAR(20),
    STATUS VARCHAR(20),
    ANALYSIS VARCHAR(100)
);
