CREATE TABLE DB2INST1.MARKET_STRESS_WATCH (
    ASSET_SYMBOL VARCHAR(10) PRIMARY KEY,
    CURRENT_PRICE DECIMAL(15,2),
    STATUS VARCHAR(20)
);
CREATE TABLE DB2INST1.DEFENSE_ENERGY_TRACE (
    ENTITY VARCHAR(30),
    ROLE VARCHAR(30),
    PRICE_BUDGET VARCHAR(20),
    STATUS VARCHAR(20),
    ANALYSIS VARCHAR(100)
);
